/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 26
#define YY_END_OF_BUFFER 27
static yyconst short int yy_accept[78] =
    {   0,
       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,
       23,   23,   23,   23,   27,   25,   23,   24,   25,   13,
        6,    2,   13,    7,   12,    1,   11,   11,    8,   14,
       23,   13,   11,   11,   15,   25,   22,   17,   25,   18,
       25,   25,   19,   20,   21,   25,    1,   23,   24,    4,
        0,    0,   12,   11,   11,   14,   23,    0,    0,    0,
        9,    0,   11,   10,   11,   15,   22,   17,   16,    0,
       21,    5,    0,    0,    0,    3,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    7,    8,    9,    9,   10,    9,
        9,    9,    9,    9,    9,    9,    9,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   12,   13,    9,
        9,    9,    9,    1,   14,   14,   14,   14,   14,   14,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
        9,   16,    9,    1,   15,   17,   18,   18,   18,   18,

       18,   18,   19,   19,   19,   19,   19,   19,   19,   20,
       19,   19,   19,   20,   19,   19,   19,   19,   19,   19,
       19,   19,   21,    9,   22,    9,    1,   23,   23,   23,
       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,
       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,
       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,
       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,
       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,
       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,
       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,

       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,
       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,
       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,
       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,
       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,
       23,   23,   23,   23,   23
    } ;

static yyconst int yy_meta[24] =
    {   0,
        1,    2,    1,    1,    3,    1,    1,    1,    1,    1,
        4,    5,    1,    6,    6,    7,    1,    8,    8,    8,
        7,    9,    1
    } ;

static yyconst short int yy_base[86] =
    {   0,
        0,   22,   41,   60,   78,    0,   19,   20,   22,   29,
       28,   30,   92,  103,  122,  195,  117,  195,  115,  195,
      195,  195,   31,  195,   39,  195,  106,   40,  195,   92,
       63,  112,  125,   55,  195,  109,    0,  195,  108,  195,
       51,   45,  195,  195,  195,  106,  195,  102,  195,   55,
       77,    0,   74,    0,    0,   68,   85,   87,   81,    0,
       82,   96,    0,  195,    0,  195,    0,  195,  195,   74,
      195,  195,   48,  101,   16,  195,  195,  145,  151,  158,
      165,  170,  173,  180,  185
    } ;

static yyconst short int yy_def[86] =
    {   0,
       77,    1,   78,   78,    4,    5,    5,    5,    5,    5,
        4,    4,    4,    4,   77,   77,   77,   77,   77,   77,
       77,   77,   79,   77,   77,   77,   77,   27,   77,   77,
       80,   81,   77,   33,   77,   77,   82,   77,   77,   77,
       79,   77,   77,   77,   77,   77,   77,   77,   77,   79,
       77,   83,   77,   27,   28,   77,   80,   81,   84,   58,
       77,   77,   33,   77,   34,   77,   82,   77,   77,   77,
       77,   77,   85,   84,   85,   77,    0,   77,   77,   77,
       77,   77,   77,   77,   77
    } ;

static yyconst short int yy_nxt[219] =
    {   0,
       16,   17,   18,   19,   20,   21,   22,   23,   20,   24,
       25,   20,   26,   27,   28,   20,   29,   27,   28,   28,
       20,   20,   30,   31,   16,   16,   32,   16,   43,   43,
       18,   19,   18,   19,   16,   33,   34,   76,   44,   33,
       34,   34,   17,   35,   36,   44,   51,   69,   70,   53,
       55,   52,   53,   55,   37,   37,   53,   55,   37,   37,
       37,   17,   35,   36,   57,   65,   51,   58,   65,   76,
       77,   52,   65,   37,   37,   77,   69,   37,   37,   37,
       38,   39,   62,   40,   53,   41,   57,   53,   60,   58,
       56,   53,   64,   42,   45,   46,   72,   62,   22,   61,

       61,   61,   62,   48,   47,   45,   46,   64,   71,   22,
       68,   66,   64,   60,   56,   47,   54,   49,   48,   54,
       55,   77,   77,   54,   55,   55,   62,   77,   77,   77,
       77,   77,   77,   77,   77,   63,   64,   77,   63,   65,
       77,   77,   63,   65,   65,   16,   16,   16,   16,   16,
       16,   16,   16,   16,   50,   77,   50,   50,   50,   59,
       59,   77,   77,   59,   77,   59,   61,   77,   77,   77,
       77,   77,   61,   67,   77,   67,   77,   67,   73,   77,
       73,   74,   77,   74,   74,   74,   77,   74,   75,   77,
       75,   77,   75,   75,   15,   77,   77,   77,   77,   77,

       77,   77,   77,   77,   77,   77,   77,   77,   77,   77,
       77,   77,   77,   77,   77,   77,   77,   77
    } ;

static yyconst short int yy_chk[219] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    2,    7,    8,    2,    9,    7,    8,
       11,   11,   12,   12,   10,    2,    2,   75,    9,    2,
        2,    2,    3,    3,    3,   10,   23,   42,   42,   25,
       28,   23,   25,   28,    3,    3,   25,   28,    3,    3,
        3,    4,    4,    4,   31,   34,   41,   31,   34,   73,
       50,   41,   34,    4,    4,   50,   70,    4,    4,    4,
        5,    5,   59,    5,   53,    5,   57,   53,   58,   57,
       56,   53,   59,    5,   13,   13,   51,   62,   13,   61,

       61,   61,   74,   48,   13,   14,   14,   62,   46,   14,
       39,   36,   74,   32,   30,   14,   27,   19,   17,   27,
       27,   15,    0,   27,   27,   27,   33,    0,    0,    0,
        0,    0,    0,    0,    0,   33,   33,    0,   33,   33,
        0,    0,   33,   33,   33,   78,   78,   78,   78,   78,
       78,   78,   78,   78,   79,    0,   79,   79,   79,   80,
       80,    0,    0,   80,    0,   80,   81,    0,    0,    0,
        0,    0,   81,   82,    0,   82,    0,   82,   83,    0,
       83,   84,    0,   84,   84,   84,    0,   84,   85,    0,
       85,    0,   85,   85,   77,   77,   77,   77,   77,   77,

       77,   77,   77,   77,   77,   77,   77,   77,   77,   77,
       77,   77,   77,   77,   77,   77,   77,   77
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "parser.L"
#define INITIAL 0
#define YY_MAIN 1
#line 4 "parser.L"
#include <stdlib.h>
#include <string.h>

#define YY_USER_INIT printf("<pre>");

int i,iskeyword;
char *keywords[] = {
	"Function",
	"FunctionEnd",
	".onGUIInit",
	".onInit",
	".onInstFailed",
	".onInstSuccess",
	".onMouseOverSection",
	".onSelChange",
	".onUserAbort",
	".onVerifyInstDir",
	"un.onGUIInit",
	"un.onInit",
	"un.onUninstFailed",
	"un.onUninstSuccess",
	"un.onUserAbort",
	"$INSTDIR",
	"$OUTDIR",
	"$0",
	"$1",
	"$2",
	"$3",
	"$4",
	"$5",
	"$6",
	"$7",
	"$8",
	"$9",
	"$R0",
	"$R1",
	"$R2",
	"$R3",
	"$R4",
	"$R5",
	"$R6",
	"$R7",
	"$R8",
	"$R9",
	"$CMDLINE",
	"$LANGUAGE",
	"$PROGRAMFILES",
	"$DESKTOP",
	"$EXEDIR",
	"${NSISDIR}",
	"$WINDIR",
	"$SYSDIR",
	"$TEMP",
	"$STARTMENU",
	"$SMPROGRAMS",
	"$SMSTARTUP",
	"$QUICKLAUNCH",
	"$HWNDPARENT",
	"$PLUGINSDIR",
	"$$",
	"$\\r",
	"$\\n",
	"Page",
	"UninstPage",
	"AddBrandingImage",
	"AllowRootDirInstall",
	"AutoCloseWindow",
	"BGGradient",
	"BrandingText",
	"Caption",
	"ChangeUI",
	"CheckBitmap",
	"CompletedText",
	"ComponentText",
	"CRCCheck",
	"DetailsButtonText",
	"DirShow",
	"DirText",
	"FileErrorText",
	"InstallButtonText",
	"InstallColors",
	"InstallDir",
	"InstallDirRegKey",
	"InstProgressFlags",
	"InstType",
	"LicenseBkColor",
	"LicenseData",
	"LicenseText",
	"LoadLanguageFile",
	"Name",
	"Icon",
	"OutFile",
	"PluginDir",
	"SetFont",
	"ShowInstDetails",
	"ShowUninstDetails",
	"SilentInstall",
	"SilentUnInstall",
	"SpaceTexts",
	"UninstallButtonText",
	"UninstallCaption",
	"UninstallIcon",
	"UninstallSubCaption",
	"UninstallText",
	"WindowIcon",
	"XPStyle",
	"SetCompress",
	"SetCompressor",
	"SetDatablockOptimize",
	"SetDateSave",
	"SetOverwrite",
	"SetPluginUnload",
	"AddSize",
	"Section",
	"SectionEnd",
	"SectionIn",
	"SubSection",
	"SubSectionEnd",
	"Delete",
	"File",
	"Exec",
	"ExecShell",
	"ExecWait",
	"Rename",
	"RMDir",
	"ReserveFile",
	"SetOutPath",
	"DeleteINISec",
	"DeleteINIStr",
	"DeleteRegKey",
	"DeleteRegValue",
	"EnumRegKey",
	"EnumRegValue",
	"ExpandEnvStrings",
	"ReadEnvStr",
	"ReadINIStr",
	"ReadRegDWORD",
	"ReadRegStr",
	"WriteINIStr",
	"WriteRegBin",
	"WriteRegDWORD",
	"WriteRegStr",
	"CallInstDLL",
	"CopyFiles",
	"CreateDirectory",
	"CreateShortCut",
	"GetDLLVersion",
	"GetDLLVersionLocal",
	"GetFileTime",
	"GetFileTimeLocal",
	"GetFullPathName",
	"GetTempFileName",
	"SearchPath",
	"SetFileAttributes",
	"RegDLL",
	"UnRegDLL",
	"Abort",
	"Call",
	"ClearErrors",
	"GetCurrentAddress",
	"GetFunctionAddress",
	"GetLabelAddress",
	"Goto",
	"IfErrors",
	"IfFileExists",
	"IfRebootFlag",
	"IntCmp",
	"IntCmpU",
	"MessageBox",
	"Return",
	"Quit",
	"SetErrors",
	"StrCmp",
	"FileClose",
	"FileOpen",
	"FileRead",
	"FileReadByte",
	"FileSeek",
	"FileWrite",
	"FileWriteByte",
	"FindClose",
	"FindFirst",
	"FindNext",
	"InitPluginsDir",
	"SetShellVarContext",
	"Sleep",
	"StrCpy",
	"StrLen",
	"Exch",
	"Pop",
	"Push",
	"IntFmt",
	"IntOp",
	"Reboot",
	"SetRebootFlag",
	"LogSet",
	"LogText",
	"SectionSetFlags",
	"SectionGetFlags",
	"SectionSetText",
	"SectionGetText",
	"BringToFront",
	"CreateFont",
	"DetailPrint",
	"FindWindow",
	"GetDlgItem",
	"HideWindow",
	"IsWindow",
	"SendMessage",
	"SetAutoClose",
	"SetBrandingImage",
	"SetDetailsView",
	"SetDetailsPrint",
	"SetStaticBkColor",
	"SetWindowLong",
	"ShowWindow",
	"LoadLanguageFile",
	"LangString",
	"LangStringUP",
	"license",
	"components",
	"directory",
	"instfiles",
	"uninstConfirm",
	"/TRIM",
	"/LANG",
	"/windows",
	"/NOCUSTOM",
	"/CUSTOMSTRING",
	"/COMPONENTSONLYONCUSTOM",
	"hide",
	"show",
	"nevershow",
	"normal",
	"silent",
	"silentlog",
	"on",
	"off",
	"auto",
	"force",
	"zlib",
	"bzip2",
	"try",
	"ifnewer",
	"manual",
	"alwaysoff",
	"/e",
	"RO",
	"/REBOOTOK",
	"/nonfatal",
	"/a",
	"/r",
	"/oname",
	"SW_SHOWNORMAL",
	"SW_SHOWMAXIMIZED",
	"SW_SHOWMINIMIZED",
	"/NOUNLOAD",
	"/SILENT",
	"/FILESONLY",
	"/SHORT",
	"MB_OK",
	"MB_OKCANCEL",
	"MB_ABORTRETRYIGNORE",
	"MB_RETRYCANCEL",
	"MB_YESNO",
	"MB_YESNOCANCEL",
	"MB_ICONEXCLAMATION",
	"MB_ICONINFORMATION",
	"MB_ICONQUESTION",
	"MB_ICONSTOP",
	"MB_TOPMOST",
	"MB_SETFOREGROUND",
	"MB_RIGHT",
	"MB_DEFBUTTON1",
	"MB_DEFBUTTON2",
	"MB_DEFBUTTON3",
	"MB_DEFBUTTON4",
	"IDABORT",
	"IDCANCEL",
	"IDIGNORE",
	"IDNO",
	"IDOK",
	"IDRETRY",
	"IDYES",
	"current",
	"all",
	"true",
	"false",
	"/TIMEOUT",
	"/IMGID",
	"/RESIZETOFIT",
	"none",
	"listonly",
	"textonly",
	"both",
	"lastused",
	"/ITALIC",
	"/UNDERLINE",
	"/STRIKE",
	"smooth",
	"MUI_PRODUCT",
	"MUI_VERSION",
	"MUI_WELCOMEPAGE",
	"MUI_LICENSEPAGE",
	"MUI_COMPONENTSPAGE",
	"MUI_DIRECTORYPAGE",
	"MUI_STARTMENUPAGE",
	"MUI_STARTMENUVARIABLE",
	"MUI_STARTMENUDEFAULTFOLDER",
	"MUI_FINISHPAGE",
	"MUI_FINISHPAGE_RUN",
	"MUI_FINISHPAGE_RUN_PARAMETERS",
	"MUI_FINISHPAGE_RUN_NOTCHECKED",
	"MUI_FINISHPAGE_SHOWREADME",
	"MUI_FINISHPAGE_SHOWREADME_NOTCHECKED",
	"MUI_FINISHPAGE_NOAUTOCLOSE",
	"MUI_FINISHPAGE_NOREBOOTSUPPORT",
	"MUI_ABORTWARNING",
	"MUI_CUSTOMPAGECOMMANDS",
	"MUI_CUSTOMGUIINIT",
	"MUI_UNINSTALLER",
	"MUI_UNCONFIRMPAGE",
	"MUI_UNCUSTOMPAGECOMMANDS",
	"MUI_UNCUSTOMGUIINIT",
	"MUI_UI",
	"MUI_ICON",
	"MUI_UNICON",
	"MUI_CHECKBITMAP",
	"MUI_FONT",
	"MUI_FONTSIZE",
	"MUI_FONT_HEADER",
	"MUI_FONTSIZE_HEADER",
	"MUI_FONTSTYLE_HEADER",
	"MUI_INSTALLCOLORS",
	"MUI_PROGRESSBAR",
	"MUI_SPECIALINI",
	"MUI_SPECIALBITMAP",
	"MUI_BGCOLOR",
	"MUI_SYSTEM",
	"MUI_LANGUAGE",
	"MUI_BRANDINGTEXT",
	"MUI_SECTIONS_FINISHHEADER",
	"MUI_UNFINISHHEADER",
	"MUI_FUNCTIONS_DESCRIPTION_BEGIN",
	"MUI_FUNCTIONS_DESCRIPTION_TEXT",
	"MUI_FUNCTIONS_DESCRIPTION_END",
	"MUI_PAGECOMMAND_WELCOME",
	"MUI_PAGECOMMAND_LICENSE",
	"MUI_PAGECOMMAND_COMPONENTS",
	"MUI_PAGECOMMAND_DIRECTORY",
	"MUI_PAGECOMMAND_INSTFILES",
	"MUI_PAGECOMMAND_FINISH",
	"MUI_UNPAGECOMMAND_CONFIRM",
	"MUI_UNPAGECOMMAND_INSTFILES",
	"MUI_INSTALLOPTIONS_EXTRACT",
	"MUI_HEADER_TEXT",
	"MUI_INSTALLOPTIONS_DISPLAY",
	"MUI_INSTALLOPTIONS_INITDIALOG",
	"MUI_INSTALLOPTIONS_SHOW",
	"MUI_INSTALLOPTIONS_READ",
	"MUI_INSTALLOPTIONS_WRITE",
	"MUI_RESERVEFILE_WELCOMEFINISHPAGE",
	"MUI_RESERVEFILE_INSTALLOPTION",
	"MUI_RESERVEFILE_LANGDLL"
};
#define SLCOMMENT 1
#define STRING 2
#define STRING2 3
#define STRING3 4
#define VAR 5
#define PREPROCESSOR 6

#line 811 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		yy_current_buffer->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 384 "parser.L"


#line 968 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 78 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 195 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;


case 1:
YY_RULE_SETUP
#line 387 "parser.L"
BEGIN(SLCOMMENT); printf("<span style=\"color:#008000\">%s",yytext);
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 388 "parser.L"
BEGIN(SLCOMMENT); printf("<span style=\"color:#008000\">%s",yytext);
	YY_BREAK


case 3:
YY_RULE_SETUP
#line 392 "parser.L"
printf("<span style=\"color:#A06000\">%s</span>",yytext);
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 393 "parser.L"
printf("<span style=\"color:#A06000\">%s</span>",yytext);
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 394 "parser.L"
printf("<span style=\"color:#A06000\">%s</span>",yytext);
	YY_BREAK


case 6:
YY_RULE_SETUP
#line 398 "parser.L"
BEGIN(STRING);	printf("<span style=\"color:#808000\">%s",yytext);
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 399 "parser.L"
BEGIN(STRING2);	printf("<span style=\"color:#808000\">%s",yytext);
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 400 "parser.L"
BEGIN(STRING3); printf("<span style=\"color:#808000\">%s",yytext);
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 402 "parser.L"
{ //preprocessor
                printf("<span style=\"color:#000080\"><b>%s</b></span>",yytext);
								BEGIN(PREPROCESSOR);
							}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 407 "parser.L"
printf("<span style=\"color:#007070\">%s</span>",yytext);
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 409 "parser.L"
{
        for(i=0,iskeyword=0; !iskeyword && i<sizeof(keywords)/sizeof(char*); i++) {
				  if(stricmp(yytext,keywords[i])==0) iskeyword=1;
        }
        if(iskeyword) {
          printf("<span style=\"color:#0000ff\">%s</span>",yytext);
        } else {
          ECHO;
        }
			}	
	YY_BREAK
/* numbers */
case 12:
YY_RULE_SETUP
#line 421 "parser.L"
printf("<span style=\"color:#000080\">%s</span>",yytext);
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 423 "parser.L"
printf("<span style=\"color:#008080\">%s</span>",yytext);
	YY_BREAK
/* invalid chars - all second part of the ASCII table */
case 14:
YY_RULE_SETUP
#line 426 "parser.L"

	YY_BREAK
case YY_STATE_EOF(INITIAL):
#line 428 "parser.L"
printf("</pre>"); yyterminate();
	YY_BREAK


case 15:
YY_RULE_SETUP
#line 432 "parser.L"
BEGIN(INITIAL); printf("%s</span>",yytext); 
	YY_BREAK


case 16:
YY_RULE_SETUP
#line 436 "parser.L"
ECHO;
	YY_BREAK
/*invalid end-of-line*/
case 17:
YY_RULE_SETUP
#line 439 "parser.L"
printf("%s</span>",yytext); BEGIN(INITIAL);
	YY_BREAK


case 18:
YY_RULE_SETUP
#line 442 "parser.L"
printf("%s</span>",yytext); BEGIN(INITIAL);
	YY_BREAK


case 19:
YY_RULE_SETUP
#line 445 "parser.L"
printf("%s</span>",yytext); BEGIN(INITIAL);
	YY_BREAK


case 20:
YY_RULE_SETUP
#line 448 "parser.L"
printf("%s</span>",yytext); BEGIN(INITIAL);
	YY_BREAK


case 21:
YY_RULE_SETUP
#line 452 "parser.L"
BEGIN(INITIAL);   ECHO;
	YY_BREAK


case 22:
#line 457 "parser.L"
case 23:
#line 458 "parser.L"
case 24:
#line 459 "parser.L"
case 25:
YY_RULE_SETUP
#line 459 "parser.L"
ECHO;
	YY_BREAK

case 26:
YY_RULE_SETUP
#line 461 "parser.L"
ECHO;
	YY_BREAK
#line 1212 "lex.yy.c"
case YY_STATE_EOF(SLCOMMENT):
case YY_STATE_EOF(STRING):
case YY_STATE_EOF(STRING2):
case YY_STATE_EOF(STRING3):
case YY_STATE_EOF(VAR):
case YY_STATE_EOF(PREPROCESSOR):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 78 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 78 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 77);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	yy_current_buffer->yy_at_bol = (c == '\n');

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 461 "parser.L"
